# waylogout(1) completion

complete -c waylogout -l cancel-label                --description "Label to display in the indicator for the cancel action."
complete -c waylogout -l cancel-shortcut             --description "Keyboard shortcut key (with optional modifiers) to select the cancel action."
complete -c waylogout -l cancel-symbol               --description "Symbol to display in the indicator for the cancel action."
complete -c waylogout -l custom-command              --description "Command to run when this custom action is activated."
complete -c waylogout -l custom-label                --description "Label to display in the indicator for this custom action."
complete -c waylogout -l custom-shortcut             --description "Keyboard shortcut key (with optional modifiers) to select this custom action."
complete -c waylogout -l custom-symbol               --description "Symbol to display in the indicator for this custom action."
complete -c waylogout -l color                  -s c --description "Turn the screen into the given color instead of white."
complete -c waylogout -l config                 -s C --description "Path to the config file."
complete -c waylogout -l debug                  -s d --description "Enable debugging output."
complete -c waylogout -l effect-blur                 --description "Blur displayed images."
complete -c waylogout -l effect-compose              --description "Overlay another image to your logout screen."
complete -c waylogout -l effect-custom               --description "Load a custom effect from a shared object."
complete -c waylogout -l effect-greyscale            --description "Make the displayed image greyscale."
complete -c waylogout -l effect-pixelate             --description "Pixelate displayed images."
complete -c waylogout -l effect-scale                --description "Scale the image by a factor."
complete -c waylogout -l effect-vignette             --description "Apply a vignette effect to images."
complete -c waylogout -l fade-in                     --description "Fade in the logout screen."
complete -c waylogout -l font                        --description "Sets the font of the action label text."
complete -c waylogout -l help                   -s h --description "Show help message and quit."
complete -c waylogout -l hibernate-command           --description "Command to run when the hibernate action is activated."
complete -c waylogout -l hibernate-label             --description "Label to display in the indicator for the hibernate action."
complete -c waylogout -l hibernate-shortcut          --description "Keyboard shortcut key (with optional modifiers) to select the hibernate action."
complete -c waylogout -l hibernate-symbol            --description "Symbol to display in the indicator for the hibernate action."
complete -c waylogout -l hide-cancel                 --description "Hide the cancel action."
complete -c waylogout -l image                  -s i --description "Display the given image, optionally only on the given output."
complete -c waylogout -l indicator-radius            --description "Sets the action indicator radius."
complete -c waylogout -l indicator-separation        --description "Sets a fixed amount of space separating action indicators."
complete -c waylogout -l indicator-thickness         --description "Sets the action indicator thickness."
complete -c waylogout -l indicator-x-position        --description "Sets the horizontal centre position of the action indicator array."
complete -c waylogout -l indicator-y-position        --description "Sets the vertical centre position of the action indicator array."
complete -c waylogout -l inside-color                --description "Sets the color of the inside of the indicator."
complete -c waylogout -l inside-selection-color      --description "Sets the color of the inside of the selected action indicator."
complete -c waylogout -l label-font-size             --description "Sets a fixed font size for the action label text."
complete -c waylogout -l labels                 -s l --description "Always show action labels."
complete -c waylogout -l line-color                  --description "Sets the color of the line between the inside and ring."
complete -c waylogout -l line-selection-color        --description "Sets the color of the line between the inside and ring in the selected action indicator."
complete -c waylogout -l line-uses-inside       -s n --description "Use the inside color for the line between the inside and ring."
complete -c waylogout -l line-uses-ring         -s r --description "Use the ring color for the line between the inside and ring."
complete -c waylogout -l lock-command                --description "Command to run when the lock action is activated."
complete -c waylogout -l lock-label                  --description "Label to display in the indicator for the lock action."
complete -c waylogout -l lock-shortcut               --description "Keyboard shortcut key (with optional modifiers) to select the lock action."
complete -c waylogout -l lock-symbol                 --description "Symbol to display in the indicator for the lock action."
complete -c waylogout -l logout-command              --description "Command to run when the logout action is activated."
complete -c waylogout -l logout-label                --description "Label to display in the indicator for the logout action."
complete -c waylogout -l logout-shortcut             --description "Keyboard shortcut key (with optional modifiers) to select the logout action."
complete -c waylogout -l logout-symbol               --description "Symbol to display in the indicator for the logout action."
complete -c waylogout -l poweroff-command            --description "Command to run when the poweroff action is activated."
complete -c waylogout -l poweroff-label              --description "Label to display in the indicator for the poweroff action."
complete -c waylogout -l poweroff-shortcut           --description "Keyboard shortcut key (with optional modifiers) to select the poweroff action."
complete -c waylogout -l poweroff-symbol             --description "Symbol to display in the indicator for the poweroff action."
complete -c waylogout -l reboot-command              --description "Command to run when the reboot action is activated."
complete -c waylogout -l reboot-label                --description "Label to display in the indicator for the reboot action."
complete -c waylogout -l reboot-shortcut             --description "Keyboard shortcut key (with optional modifiers) to select the reboot action."
complete -c waylogout -l reboot-symbol               --description "Symbol to display in the indicator for the reboot action."
complete -c waylogout -l reload-command              --description "Command to run when the reboot action is activated."
complete -c waylogout -l reload-label                --description "Label to display in the indicator for the reload session action."
complete -c waylogout -l reload-shortcut             --description "Keyboard shortcut key (with optional modifiers) to select the reload action."
complete -c waylogout -l reload-symbol               --description "Symbol to display in the indicator for the reload session action."
complete -c waylogout -l ring-color                  --description "Sets the color of the ring of the action indicators."
complete -c waylogout -l ring-selection-color        --description "Sets the color of the ring of the selected action indicator."
complete -c waylogout -l rows                   -s R --description "Number of rows of action indicators to display."
complete -c waylogout -l scaling                -s s --description "Image scaling mode."
complete -c waylogout -l screenshots            -s S --description "Display a screenshot."
complete -c waylogout -l scroll-sensitivity          --description "How fast selected action will change when scrolling with mouse/touch."
complete -c waylogout -l instant-run                 --description "Instantly run actions on key press, without confirmation with enter key."
complete -c waylogout -l selection-label             --description "Show action label for selected action."
complete -c waylogout -l suspend-command             --description "Command to run when the suspend action is activated."
complete -c waylogout -l suspend-label               --description "Label to display in the indicator for the suspend action."
complete -c waylogout -l suspend-shortcut            --description "Keyboard shortcut key (with optional modifiers) to select the suspend action."
complete -c waylogout -l suspend-symbol              --description "Symbol to display in the indicator for the suspend action."
complete -c waylogout -l switch-user-command         --description "Command to run when the switch-user action is activated."
complete -c waylogout -l switch-user-label           --description "Label to display in the indicator for the switch user action."
complete -c waylogout -l switch-user-shortcut        --description "Keyboard shortcut key (with optional modifiers) to select the switch user action."
complete -c waylogout -l switch-user-symbol          --description "Symbol to display in the indicator for the switch user action."
complete -c waylogout -l symbol-font-size            --description "Sets a fixed font size for the action symbols."
complete -c waylogout -l text-color                  --description "Sets the color of the text."
complete -c waylogout -l text-selection-color        --description "Sets the color of the text for the selected action indicator."
complete -c waylogout -l tiling                 -s t --description "Same as --scaling=tile."
complete -c waylogout -l time-effects                --description "Measure the time it takes to run each effect."
complete -c waylogout -l version                -s v --description "Show the version number and quit."
